sudo: true
language: ruby
rvm: 2.3.1
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - GIT_COMMITTER_NAME='fullvirtue@travis-ci'
  - GIT_COMMITTER_EMAIL='fullvirtue@gmail.com'
  - GIT_AUTHOR_NAME='fullvirtue@travis-ci'
  - GIT_AUTHOR_EMAIL='fullvirtue@gmail.com'
  - TRAVIS_NODE_VERSION="6.1"
  - secure: WQjBFk5r7aT7zjsro6HFy2Zhre3RFZgzNI8rhbZTivegxafVydvI/PAxW5Ahq6z+golhp5d6BqD4NnO/OzqjzwGVXQ2QumE20kpRxbgmqRzTUSTm6f9a93vSV/V/2Jxttc0cjaiNRymSp4k2Ev+5yRsjPw3UoX35+fLRt4FOrtzGtuIcwCO7Z/BOC1Ob2/OKQlkgW7yAOZ0McwSZcIcMAZiokNv5Yv+5C756PEuTvsVA8duhIVSbhuyvz1N+6UuYFrga+bsCKnoKTvPmQOD2ZDdsNAEjUjLItKzykTHJfNfmcfFJEmEZ9fVuZPosYLa8j47k0eutu7Uzh+SOI+QfUkmL24i2D2ceOoGifEZrPI5chH4CsoF+kJH1x0UUfZPd92HOIZtoU+iFnDNVY5lrIEgzwe4o8Qnsjo/HgIwdMKWGWGmduXjg9cOGiczRjXvUsu+rXmwWWSQhf11dE4JrlUH0n2dn2DDnc9NJ36DHIe64yhej/uWGd7fO3R7jE8fXQ+2xZzfAjnzXgYoIb96LcXif+3FC5+33K6xEKFa/SqczjlbcLjvepHS2MVYOEeI/XX9AOarz2+tyHJaba9EMo0a6ChuFzeEbWQz7txGLRssSZ4H0QXqN6TBA66t2c+FNEs5vUriFRTiwQ8YJwkrqkfRaayKEGfyNdb+iMSuHgqg=
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install
script:
- bundle exec middleman build --verbose
after_success:
- '[ "$TRAVIS_BRANCH" == "dev" ] && [ $GH_TOKEN ] && bundle exec middleman deploy --verbose'
